
# -*- mode: ruby -*-
# vi: set ft=ruby :


domain = 'cheekuru.com'
box = 'bento/ubuntu-18.04'


puppet_nodes = [
      {:hostname => 'sample-ubuntu',  :ip => '172.16.32.11', :ram => 2048, :master=>true},
]


Vagrant.configure("2") do |config|

  puppet_nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = box
      #node_config.vm.box_url = 'https://atlas.hashicorp.com/' + node_config.vm.box
      node_config.vm.hostname = node[:hostname] + '.' + domain
      node_config.vm.network :private_network, ip: node[:ip]

      memory = node[:ram] ? node[:ram] : 512;
      node_config.vm.provider :virtualbox do |vb|
        vb.memory = memory
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--groups", "/cheekuru-devops"]
        vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
      end
      node_config.vm.provision "shell", inline:  "apt-get update -y"
      node_config.vm.provision "shell", inline:  "apt install git -y"
    end
  end
end
