
# -*- mode: ruby -*-
# vi: set ft=ruby :


domain = 'cheekuru.com'
box = 'centos/7'


checkmk_nodes = [
    {:hostname => 'checkmk-master',  :ip => '172.16.20.60', :ram => 2048, :master=>true},
    {:hostname => 'east-host-1',  :ip => '172.16.20.61', :ram => 1024, :master=>false},
    {:hostname => 'east-host-2',  :ip => '172.16.20.62', :ram => 1024, :master=>false},

]


Vagrant.configure("2") do |config|

  checkmk_nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = box
      #node_config.vm.box_url = 'https://atlas.hashicorp.com/' + node_config.vm.box
      node_config.vm.hostname = node[:hostname] + '.' + domain
      node_config.vm.network :private_network, ip: node[:ip]

      memory = node[:ram] ? node[:ram] : 512;
      node_config.vm.provider :virtualbox do |vb|
        vb.memory = memory
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--groups", "/cheekuru-devops"]
        vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
      end

      node_config.vm.provision "file", source: "config", destination: "devops"
      node_config.vm.provision "shell", path: "shell/default-provision.sh"
      if node[:master]
        print "Checkmk master machine is bootstrapping \n"
        node_config.vm.provision "file", source: "selinux", destination: "devops/selinux"
        node_config.vm.provision "shell", path: "shell/checkmk-bootstrap.sh"
      else
        print "Started building a backend machine   \n"
        node_config.vm.provision "shell", path: "shell/node-bootstrap.sh"
      end

    config.vm.provision :hosts do |provisioner|
      provisioner.add_host '172.16.20.60' , ['checkmk-master.cheekuru.com', 'ansible']
      provisioner.add_host '172.16.20.61' , ['east-host-1.cheekuru.com', 'east-host-1']
      provisioner.add_host '172.16.20.62' , ['east-host-2.cheekuru.com', 'east-host-2']

    end
     # end
    end
  end
end
