Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = 'linuxfoundation-centos.cheekuru.com'
  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provision "shell", inline: <<-SHELL
     yum update -y
     yum install wget -y
  SHELL
end
