# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"

    config.vm.define :jenkins do |jenkins_config|
        jenkins_config.vm.hostname = 'jenkins.cheekuru.com'
        jenkins_config.vm.network "private_network", ip: "192.168.10.11"
    end

    config.vm.provider :virtualbox do |virtualbox_config|
        virtualbox_config.name = "Jenkins - Ubuntu 18.04"
    end

    config.vm.provision :shell, path: "bootstrap.sh"

    config.vm.synced_folder "", "/jenkins", nfs: true, mount_options: ["actimeo=2"]
end
